### PR TITLE
Added "onCheckedChild" and "onCheckedParent" functions, Version 2

### PR DESCRIPTION
**Pull request by DavidWoli**
I added this functionality because I needed it myself.
I am making the pull request because I think other users probably also would need this functionality.

So just merge it, please.

### CODE REVIEW

**Comment by DavidWoli** [comment]
@AbhishekDoshi26 Here it is. Close the other RP and merge this one.

**Review by AbhishekDoshi26 — APPROVED** [review]

**Comment by DavidWoli** [comment]
@AbhishekDoshi26  will you bring a new version to flutter pub with just merged features?

**Comment by AbhishekDoshi26** [comment]
@DavidWoli yess I will deploy a new version in maybe 1h.

**Comment by DavidWoli** [comment]
@AbhishekDoshi26 Do not forget to add those features to the README.md table!

**Comment by AbhishekDoshi26** [comment]
haha yepp. I was just doing that. New version published on pub.dev :)
CC: @DavidWoli

**Pull request merged**
