### PR TITLE
Just added "onCheckedChild"  and "onCheckedParent" functions

### PR DESCRIPTION
**Pull request by davidCpp16**
I added this functionality because I needed it myself.
I am making the pull request because I think other users probably also would need this functionality.

So just merge it, please.

### CODE REVIEW

**Comment by AbhishekDoshi26** [comment]
@davidCpp16 sorry for the delay. Thank You for the PR. Can you solve the merge conflicts and we are good to go?

Thanks!

**Comment by DavidWoli** [comment]
@AbhishekDoshi26 I would like to solve the conflicts, but I do not have the access to the @davidCpp16 account anymore. Could you somehow solve it on your own?

**Comment by AbhishekDoshi26** [comment]
@DavidWoli maybe create a new PR?

**Comment by DavidWoli** [comment]
@AbhishekDoshi26 do you mean from @DavidWoli account?

**Comment by AbhishekDoshi26** [comment]
> @AbhishekDoshi26 do you mean from @DavidWoli account?

Yep yep yep yep

**Comment by AbhishekDoshi26** [comment]
Closing because a new PR #7 is opened

**Pull request closed without merging**
